In [8]:
import numpy as np

In [9]:
def G(x):
    grad = np.zeros(4).reshape(4,1)
    grad[0] = 2 * (x[0] + 10 * x[1]) + 40 * (x[0] - x[3]) ** 3
    grad[1] = 20 * (x[0] + 10 * x[1]) + 4 * (x[1] - 2 * x[2]) ** 3
    grad[2] = 10 * (x[2] - x[3]) - 8 * (x[1] - 2 * x[2]) ** 3
    grad[3] = -10 * (x[2] - x[3]) - 40 * (x[0] - x[3]) ** 3
    return grad

In [10]:
x = np.array([3,-1,0,1]).reshape(4,1)
g = G(x)
print(g)

[[ 306.]
 [-144.]
 [  -2.]
 [-310.]]


In [11]:
def H(x):
    hes = np.zeros([4,4])
    hes[0][0] = 2 + 120 * (x[0] - x[3]) ** 2
    hes[0][1] = 20
    hes[0][3] = -120 * (x[0] - x[3]) ** 2
    hes[1][0] = 20
    hes[1][1] = 200 + 12 * (x[1] - 2 * x[2]) ** 2
    hes[1][2] = -24 * (x[1] - 2 * x[2]) ** 2
    hes[2][1] = -24 * (x[1] - 2 * x[2]) ** 2
    hes[2][2] = 10 + 48 * (x[1] - 2 * x[2]) ** 2
    hes[2][3] = -10
    hes[3][0] = -120 * (x[0] -x[3]) ** 2
    hes[3][2] = -10
    hes[3][3] = 10 + 120 * (x[0] - x[3]) ** 2
    return hes

In [12]:
h = H(x)
h_inv = np.linalg.inv(h)
print(h)
print(h_inv)

[[ 482.   20.    0. -480.]
 [  20.  212.  -24.    0.]
 [   0.  -24.   58.  -10.]
 [-480.    0.  -10.  490.]]
[[ 0.11262283 -0.00888133  0.0154006   0.1106387 ]
 [-0.00888133  0.00565004  0.00084089 -0.00868292]
 [ 0.0154006   0.00084089  0.02026172  0.01549981]
 [ 0.1106387  -0.00868292  0.01549981  0.11073791]]


In [13]:
x = np.array([3,-1,0,1]).reshape(4,1)
for i in range(3):
    print('iteration',i+1)
    h = H(x)
    print('h = ',h)
    g = G(x)
    print('g = ',g)
    h_inv = np.linalg.inv(h)
    print('h_inv = ',h_inv)
    x = x - np.matmul(h_inv,g)
    print('x_new = ',x)

iteration 1
h =  [[ 482.   20.    0. -480.]
 [  20.  212.  -24.    0.]
 [   0.  -24.   58.  -10.]
 [-480.    0.  -10.  490.]]
g =  [[ 306.]
 [-144.]
 [  -2.]
 [-310.]]
h_inv =  [[ 0.11262283 -0.00888133  0.0154006   0.1106387 ]
 [-0.00888133  0.00565004  0.00084089 -0.00868292]
 [ 0.0154006   0.00084089  0.02026172  0.01549981]
 [ 0.1106387  -0.00868292  0.01549981  0.11073791]]
x_new =  [[ 1.58730159]
 [-0.15873016]
 [ 0.25396825]
 [ 0.25396825]]
iteration 2
h =  [[ 215.33333333   20.            0.         -213.33333333]
 [  20.          205.33333333  -10.66666667    0.        ]
 [   0.          -10.66666667   31.33333333  -10.        ]
 [-213.33333333    0.          -10.          223.33333333]]
g =  [[ 94.81481481]
 [ -1.18518519]
 [  2.37037037]
 [-94.81481481]]
h_inv =  [[ 0.13860544 -0.01147959  0.03890306  0.13414116]
 [-0.01147959  0.00590986 -0.00150935 -0.01103316]
 [ 0.03890306 -0.00150935  0.04388818  0.03912628]
 [ 0.13414116 -0.01103316  0.03912628  0.13436437]]
x_new =  [