In [11]:

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import itertools


In [12]:
def Q(x):
    a11=1200*x[0]**2-400*x[1]+2
    a12=-400*x[0]
    a21=-400*x[0]
    a22=200
    A=np.zeros([2,2])
    A[0][0]=a11
    A[0][1]=a12
    A[1][0]=a21
    A[1][1]=a22
    return A

In [22]:
x=np.array([[-2],[3]])
print(g(x))
A=Q(x)
print(x)
print(A)

[[-3998.]
 [ -800.]]
[[-2]
 [ 3]]
[[3602.  800.]
 [ 800.  200.]]


In [13]:
def B(x):
    b=np.zeros([2,1])
    b[0][0]=400*x[0]**3-400*x[0]*x[1]+2*x[0]-2
    b[1][0]=200*(x[1]-x[0]**2)
    return b

In [14]:
def f(x,c):
    A=Q(x)
    b=B(x)
    return 0.5 * x.T @ A @ x - x.T@b + c

In [15]:
c=1
f(x, c)

array([[2793.]])

In [16]:
def g(x):
    A=Q(x)
    b=B(x)
    return A @ x - b 

In [17]:
def Beta(x_cur,x_new,d_cur):
    return g(x_new).T@Q(x_cur)@d_cur/d_cur.T@Q(x_cur)@d_cur


In [18]:
def Alpha(x,d_cur):
    return -1*g(x).T@d_cur/d_cur.T@Q(x)@d_cur

In [19]:
# def d(x_new,x_cur):
#     return -1*g(x_new)+Beta(x_cur,x_new)*d(x_cur)

In [20]:
x_cur=np.array([[1],[1]])
g_cur=g(x_cur)
ginit=g_cur
print(g_cur)
d_cur=-1 * g_cur

for k in range(8):
    print('iter',k+1)
    alpha=-1*g(x_cur).T@d_cur/(d_cur.T@Q(x_cur)@d_cur)
    print('alpha',alpha)
    x_new=x_cur+alpha*d_cur
    g_new=g(x_new)
    beta=g_new.T@Q(x_cur)@d_cur / (d_cur.T @Q(x_cur)@d_cur)
    d_new=-g_new+beta*d_cur
    print('x',x_new)
    print('g',g_new)
#     print(d_new)
    x_cur=x_new
    if k+1<7:
        d_cur=-g(x_cur)
    else:
        d_cur=d_new

    

[[ 402.]
 [-200.]]
iter 1
alpha [[0.0009984]]
x [[0.59864186]
 [1.19968067]]
g [[-113.64240626]
 [ -71.67441475]]
iter 2
alpha [[-0.00517084]]
x [[0.01101471]
 [0.82906346]]
g [[-1.65168983]
 [-0.02426479]]
iter 3
alpha [[-0.00303495]]
x [[0.00600192]
 [0.82898982]]
g [[ 0.00996   ]
 [-0.00720461]]
iter 4
alpha [[-0.00687908]]
x [[0.00607044]
 [0.82894025]]
g [[-0.01263317]
 [-0.00737004]]
iter 5
alpha [[-0.00507135]]
x [[0.00600637]
 [0.82890288]]
g [[ 0.0086942]
 [-0.0072153]]
iter 6
alpha [[-0.00899294]]
x [[0.00608456]
 [0.82883799]]
g [[-0.01706461]
 [-0.00740437]]
iter 7
alpha [[-0.00404244]]
x [[0.00601557]
 [0.82880806]]
g [[ 0.00587155]
 [-0.00723743]]
iter 8
alpha [[0.00294149]]
x [[0.00602383]
 [0.82884043]]
g [[ 0.00305622]
 [-0.00725731]]
